releases:
- name:    shield
  version: 9.3.0-rc.1
  url:     https://github.com/shieldproject/shield-boshrelease/releases/download/v9.3.0-rc.1/shield-boshrelease-9.3.0-rc.1.tgz
  sha1:   bf350d15620a6633cac520a6d01547037488a04a
