- type: replace
  path: /releases?/name=shield?
  value:
    name: shield
    version: 8.7.4
    url: https://bosh.io/d/github.com/starkandwayne/shield-boshrelease?v=8.7.4
    sha1: e903af864cf0afdec83950431fcbd6b6a10395ee
