releases:
- name:    shield
  version: 9.3.0
  url:     https://github.com/shieldproject/shield-boshrelease/releases/download/v9.3.0/shield-boshrelease-9.3.0.tgz
  sha1:    c229a2fe681d9c4bd42271b461a4bfaea5f3ce7d
