releases:
- name:    shield
  version: 9.2.0-rc2
  url:     https://github.com/shieldproject/shield-boshrelease/releases/download/v9.2.0-rc2/shield-boshrelease-9.2.0-rc2.tgz
  sha1:    0748d4b4b209927bde1687c2c83e350a172d029b
