releases:
- name:    shield
  version: 9.4.0
  url:     https://github.com/shieldproject/shield-boshrelease/releases/download/v9.4.0/shield-boshrelease-9.4.0.tgz
  sha1:    6671264cd7d3ca947639389630496e69d280c5aa
