- type: replace
  path: /releases?/name=shield-addon-postgres?
  value:
    name: shield-addon-postgres
    version: 2.0.0
    url:     https://github.com/shieldproject/shield-addon-postgres-boshrelease/releases/download/v2.0.0/shield-addon-postgres-2.0.0.tgz
    sha1:    5326d009a36fab7e21198bc1b9ef5dc13c93a848
