#!/bin/bash
set -eu

declare -a merge

validate_features \
  ocfp oauth oauth-provider \
  proxy postgres-addon secure

# ocfp feature here
if want_feature "ocfp" ; then
  merge=( 
    "ocfp/meta.yml"
    "ocfp/ocfp.yml"
    "manifests/releases/shield.yml"
  )
else
  merge=( 
    "manifests/shield.yml"
    "manifests/releases/shield.yml"
  )

  if want_feature postgres-addon ; then 
    merge+=( 
    "manifests/addons/postgres.yml"
    "manifests/releases/shield-addon-postgres.yml"
    )
  fi

  if want_feature secure ; then
    merge+=( "manifests/addons/secure.yml" )
  fi
fi

want_feature oauth && merge+=( manifests/oauth.yml )

# TODO: Add `ops/` file support here

if want_feature oauth-provider; then
  echo >&2 "The oauth-provider feature flag is now just called 'oauth'."
  merge+=( "manifests/oauth.yml" )
fi

if want_feature proxy; then
  echo >&2 "You no longer need to explicitly specify the 'proxy' feature."
  echo >&2 "If you remove it, everything will still work as expected."
fi

echo "${merge[@]}"
