#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  if want_feature ocfp ; then
    _env_scale="$(lookup --merged meta.ocfp.env.scale)"
    _vm_type="shield-${_env_scale}"
    _network="${GENESIS_ENVIRONMENT}-shield"
    _disk_type="shield-${_env_scale}"
  else # Legacy was hard coded
    _vm_type="small"
    _network="shield"
    _disk_type="shield"
  fi

  cloud_config_needs vm_type   "$(lookup params.shield_vm_type   ${_vm_type})"
  cloud_config_needs network   "$(lookup params.shield_network   ${_network})"
  cloud_config_needs disk_type "$(lookup params.shield_disk_pool ${_disk_type})"

  if check_cloud_config; then
    describe "  cloud config [#G{OK}]"
  else
    describe "  cloud config [#R{FAILED}]"
    exit 1
  fi
fi
