#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  cloud_config_needs vm_type    "$(lookup params.shield_vm_type    small)"
  cloud_config_needs disk_type  "$(lookup params.shield_disk_pool  shield)"
  cloud_config_needs network    "$(lookup params.shield_network    shield)"
  if check_cloud_config; then
    describe "  cloud config [#G{OK}]"
  else
    describe "  cloud config [#R{FAILED}]"
    exit 1
  fi
fi
