#!/bin/bash
set -eu

    echo "----------------------------------------------------"
    echo "$GENESIS_ENVIRONMENT SHIELD core"
    echo "  $(lookup params.installation 'S.H.I.E.L.D.')"
    echo
describe "endpoint information"
    echo "  https://$(lookup params.shield_static_ip)"
    echo
describe "default credentials"
    echo "  username: admin"
    echo "  password: shield"
    echo
    echo "----------------------------------------------------"
    echo
