#!/bin/bash
set -eu

# TODO: Fix lookup params.installation below for ocfp

if want_feature ocfp; then
  core_name=$(lookup meta.core.name)
else
  core_name=$(lookup params.installation 'S.H.I.E.L.D.')
fi

describe \
  "" \
  "#B${core_name}" \
  "" \
  "endpoint information" \
  "  #C{$(exodus url)}" \
  "" \
  "admin credentials" \
  "  username: #M{$(exodus admin_username)}" \
  "  password: #G{$(exodus admin_password)}"
