#!/bin/bash
set -eu

describe "" \
         "#B{$(lookup params.installation 'S.H.I.E.L.D.')}" \
         "" \
         "endpoint information" \
         "  #C{$(exodus url)}" \
         "" \
         "default credentials" \
         "  username: #M{admin}" \
         "  password: #G{shield}"
