#!/bin/bash
set -eu

ip= # assigned below with prompt_for
prompt_for ip line \
	'What IP address would you like to deploy SHIELD on?'

external_domain= # assugbed below with prompt_for
prompt_fo external_domain line \
  'What domain name would you like to use? (leave blank to just use IP)' \
  --default ''

isoauth= # assigned below with prompt_for
prompt_for isoauth boolean \
	'Would you like to authenticate against an OAuth2 endpoint (Github / UAA)?'

(
echo "---"
echo "kit:"
echo "  name:    $GENESIS_KIT_NAME"
echo "  version: $GENESIS_KIT_VERSION"
if [[ $isoauth == 'true' ]]; then
	echo "  features:"
	echo "    - oauth"
else
	echo "  features: []"
fi
echo ""
genesis_config_block

echo "params:"
echo "  shield_static_ip: $ip"
[[ -n "$external_domain" ]] && echo "  external_domain: $external_domain"
) > "$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml"
