---
meta:
  # NOTE: vvv next genesis rc will have these 3  built in, remove then
  vault_env:         (( grab $GENESIS_SECRETS_SLUG ))
  vault_mount:       (( grab $GENESIS_SECRETS_MOUNT ))
  vault_exodus_path: (( grab $GENESIS_EXODUS_MOUNT ))
  # NOTE: ^^^

  ocfp:
    env:
      scale: (( grab params.env.scale || "dev" ))

    vault:
      tf: (( concat meta.vault_mount "tf/" meta.vault_env ))

    certs:
      trusted:
        - (( vault meta.vault_mount "/certs/org:ca" )) # Organization CA, if exists
        - (( vault meta.vault_mount "/certs/dbs:ca" )) # External Databases CA

  stemcell:
    name:    (( grab params.stemcell_name    || "bionic" ))
    os:      (( grab params.stemcell_os      || "ubuntu-bionic" ))
    version: (( grab params.stemcell_version || "latest" ))

  shield:
    ip:     (( vault meta.ocfp.vault.tf "/bosh/iaas/subnets/ocfp/0/ips/mgmt/reserved:shield_ip" ))
    az:     (( vault meta.ocfp.vault.tf "/bosh/iaas/subnets/ocfp/0:availability_zone" ))
    domain: (( vault meta.ocfp.vault.tf "/net/shield:fqdn" ))
    ca:     (( vault meta.vault         "/certs/ca:certificate" ))

    admin:
      username: (( vault meta.ocfp.vault.tf "/shield/admin:username" ))
      password: (( vault meta.ocfp.vault.tf "/shield/admin:password" ))


    url:        (( concat "https://" meta.shield.domain ))
    disk_type:  (( concat "shield-" meta.ocfp.env.scale ))
    vm_type:    (( concat "shield-" meta.ocfp.env.scale ))
    network:    (( concat genesis.env "-shield" ))

    agent:
      pub:      (( vault meta.vault "/agent:public" ))
      key:      (( vault meta.vault "/agent:private" ))

    server:
      cert:     (( vault meta.vault "/certs/server:certificate" ))
      key:      (( vault meta.vault "/certs/server:key" ))

    vault:
      ca:       (( vault meta.vault "/vault/ca:certificate" ))
      cert:     (( vault meta.vault "/vault/server:certificate" ))
      key:      (( vault meta.vault "/vault/server:key" ))

    core:
      name: (( concat meta.env.name "-shield" ))

