---
meta:
  env_name:          (( grab $GENESIS_ENVIRONMENT ))
  env_slug:          (( grab $GENESIS_SECRETS_SLUG ))
  env_scale:         (( grab params.env_scale || "dev" ))
  vault_mount:       (( grab $GENESIS_SECRETS_MOUNT ))
  vault_exodus_path: (( grab $GENESIS_EXODUS_MOUNT ))
  vault_tf_path:     (( concat meta.vault_mount "tf/" meta.env_slug ))
  vault_env_path:    (( concat meta.vault_mount meta.env_slug ))
  vault_certs_path:  (( concat meta.vault_mount "certs" ))

  trusted_certs:
    - (( vault meta.vault_certs_path "/org:ca" )) # Organization CA, if exists
    - (( vault meta.vault_certs_path "/dbs:ca" )) # External Databases CA

  stemcell:
    name:    (( grab params.stemcell_name    || "bionic" ))
    os:      (( grab params.stemcell_os      || "ubuntu-bionic" ))
    version: (( grab params.stemcell_version || "latest" ))

  shield:
    ip:     (( vault meta.vault_tf_path "/bosh/iaas/subnets/ocfp/0/ips/mgmt/reserved:shield_ip" ))
    az:     (( vault meta.vault_tf_path "/bosh/iaas/subnets/ocfp/0:availability_zone" ))
    domain: (( vault meta.vault_tf_path "/net/shield:fqdn" ))
    ca:     (( vault meta.vault "/certs/ca:certificate" ))

    admin:
      username: (( vault meta.vault_tf_path "/shield/admin:username" ))
      password: (( vault meta.vault_tf_path "/shield/admin:password" ))


    url:        (( concat "https://" meta.shield.domain ))
    disk_type:  (( concat "shield-" meta.env_scale ))
    vm_type:    (( concat "shield-" meta.env_scale ))
    network:    (( concat meta.env.name "-shield" ))

    agent:
      pub:      (( vault meta.vault "/agent:public" ))
      key:      (( vault meta.vault "/agent:private" ))

    server:
      cert:     (( vault meta.vault "/certs/server:certificate" ))
      key:      (( vault meta.vault "/certs/server:key" ))

    vault:
      ca:       (( vault meta.vault "/vault/ca:certificate" ))
      cert:     (( vault meta.vault "/vault/server:certificate" ))
      key:      (( vault meta.vault "/vault/server:key" ))

    core:
      name: (( concat meta.env.name "-shield" ))

