---
meta:
  ocfp:
    env:
#      az:     (( grab params.availability_zones[0] || "z1" ))
      subnet: (( grab params.ocfp_subnet || "ocfp-0" ))

    vault:
      config_slug:   (( grab params.ocfp_vault_config_slug || genesis.ocfp_env ))
      config:        (( concat genesis.ocfp_config_mount meta.ocfp.vault.config_slug ))

    certs:
      trusted:
        - (( append ))
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA

  stemcell:
    name:    (( grab params.stemcell_name    || "default" ))
    os:      (( grab params.stemcell_os      || "ubuntu-jammy" ))
    version: (( grab params.stemcell_version || "latest" ))

  shield:
    ip:     (( vault meta.ocfp.vault.config "/vpc/subnets/" meta.ocfp.env.subnet "/reserved-ips:shield_ip" ))
    az:     (( concat genesis.env "-z1" ))
    domain: (( vault meta.ocfp.vault.config "/fqdns:shield" ))
    ca:     (( vault meta.vault         "/certs/ca:certificate" ))

    url:        (( concat "https://" meta.shield.domain ))
    disk_type:  (( concat genesis.env ".shield.disk-shield" ))
    vm_type:    (( concat genesis.env ".shield.vm-shield" ))
    network:    (( concat genesis.env ".shield.net-shield" ))

    agent:
      pub:      (( vault meta.vault "/agent:public" ))
      key:      (( vault meta.vault "/agent:private" ))

    server:
      cert:     (( vault meta.vault "/certs/server:certificate" ))
      key:      (( vault meta.vault "/certs/server:key" ))

    vault:
      ca:       (( vault meta.vault "/vault/ca:certificate" ))
      cert:     (( vault meta.vault "/vault/server:certificate" ))
      key:      (( vault meta.vault "/vault/server:key" ))

    core:
      name: (( concat genesis.env "-shield" ))

