---
meta:
  ocfp:
    env:
      scale: (( grab params.ocfp_env_scale || "dev" ))

    vault:
      config_prefix: (( grab params.ocfp_vault_config_prefix || "config/" ))
      config: (( concat genesis.ocfp_config_mount genesis.ocfp_env ))

    # certs.trusted for Org and DBs woudl be added here

  stemcell:
    name:    (( grab params.stemcell_name    || "default" ))
    os:      (( grab params.stemcell_os      || "ubuntu-jammy" ))
    version: (( grab params.stemcell_version || "latest" ))

  shield:
    ip:     (( vault meta.ocfp.vault.config "/vpc/subnets/ocfp-0/reserved-ips:shield_ip" ))
    az:     (( concat genesis.env "-z1" ))
    domain: (( vault meta.ocfp.vault.config "/fqdns:shield" ))
    ca:     (( vault meta.vault         "/certs/ca:certificate" ))

    admin:
      username: (( vault meta.ocfp.vault.config "/shield/admin:username" ))
      password: (( vault meta.ocfp.vault.config "/shield/admin:password" ))


    url:        (( concat "https://" meta.shield.domain ))
    disk_type:  (( concat genesis.env ".shield.disk-shield" ))
    vm_type:    (( concat genesis.env ".shield.vm-shield" ))
    network:    (( concat genesis.env ".shield.net-shield" ))

    agent:
      pub:      (( vault meta.vault "/agent:public" ))
      key:      (( vault meta.vault "/agent:private" ))

    server:
      cert:     (( vault meta.vault "/certs/server:certificate" ))
      key:      (( vault meta.vault "/certs/server:key" ))

    vault:
      ca:       (( vault meta.vault "/vault/ca:certificate" ))
      cert:     (( vault meta.vault "/vault/server:certificate" ))
      key:      (( vault meta.vault "/vault/server:key" ))

    core:
      name: (( concat genesis.env "-shield" ))

