---
meta:
  kit:     shield
  release: S.H.I.E.L.D. Genesis Kit
  target:  buf
  url:     https://10.200.131.2.netip.cc

  initial_version: 0.3.0

  bosh:
    uri:      (( vault "secret/pipelines/genesis-ci/bosh:uri" ))
    username: (( vault "secret/pipelines/genesis-ci/admin:username" ))
    password: (( vault "secret/pipelines/genesis-ci/admin:password" ))
    cacert:   (( vault "secret/pipelines/genesis-ci/ca:certificate" ))

  vault:
    url:   https://10.200.130.4
    token: (( vault "secret/pipelines/vault:token" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  genesis-community
    repo:   shield-genesis-kit
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github/genesis-bot:private" ))
    access_token: (( vault "secret/pipelines/shared/github/genesis-bot:access_token" ))

  slack:
    webhook:  (( vault "secret/slack/botspam:webhook" ))
    channel:  '#botspam'
    username: starkandwayne-ci
    icon:     https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
