---
instance_groups:
  - name: shield
    jobs:
      - name: core
        properties:
          auth:
          - identifier: okta # or whatever you used when registering
            name:       Okta
            backend:    okta
            properties:
              client_id:            (( vault meta.vault "/okta:client_id" ))
              client_secret:        (( vault meta.vault "/okta:client_secret" ))
              # NOTE: domain + auth_server === issuer
              okta_domain:          (( vault meta.vault "/okta:domain" ))
              authorization_server: (( vault meta.vault "/okta:auth_server" ))
              deployment_uri:       (( vault meta.vault "" )) # SHIELD-DEPLOYMENT-URL
              mapping:  []    # more on this later
        
